#!/bin/bash
#PBS -N star_index_sus_scrofa
#PBS -l nodes=1:ppn=12,mem=100gb,walltime=24:00:00
#PBS -q high_mem
#PBS -m ae
#PBS -M seuemail@dominio.com

# Ir para o diretório de trabalho do job
cd $PBS_O_WORKDIR

# Carregar módulos
source /etc/profile.d/modules.sh
module load star/2.7.9a

# Caminhos dos arquivos no cluster
GENOME_FA="/home/ps11038/genoma/Sus_scrofa.Sscrofa11.1.dna_rm.toplevel.fa"
GTF_FILE="/home/ps11038/genoma/Sus_scrofa.Sscrofa11.1.111.gtf"
INDEX_DIR="/home/ps11038/genoma/IndexedGenome"

# Criar diretório de índice se não existir
mkdir -p $INDEX_DIR

# Criando índice STAR
STAR \
  --runThreadN 12 \
  --runMode genomeGenerate \
  --genomeDir $INDEX_DIR \
  --genomeFastaFiles $GENOME_FA \
  --sjdbGTFfile $GTF_FILE \
  --sjdbOverhang 149
